-- Auto-generated from src/lib/permCatalog.js — idempotent catalog seed.
INSERT INTO public.permissions
  (module, module_label_ar, module_icon, module_sort, action, label_ar, sort_order, is_active)
VALUES
('home', 'الرئيسية', 'home', 10, 'view', 'عرض اللوحة', 0, true),
('facilities', 'المنشآت', 'facility', 20, 'view', 'عرض المنشآت', 0, true),
('facilities', 'المنشآت', 'facility', 20, 'create', 'إضافة منشأة', 10, true),
('facilities', 'المنشآت', 'facility', 20, 'edit', 'تعديل المنشآت', 20, true),
('facilities', 'المنشآت', 'facility', 20, 'delete', 'حذف المنشآت', 30, true),
('facilities', 'المنشآت', 'facility', 20, 'sync', 'مزامنة المنشآت', 40, true),
('workers', 'العمالة الدائمة', 'labor', 30, 'view', 'عرض العمالة', 0, true),
('workers', 'العمالة الدائمة', 'labor', 30, 'create', 'إضافة عامل', 10, true),
('workers', 'العمالة الدائمة', 'labor', 30, 'edit', 'تعديل العمالة', 20, true),
('workers', 'العمالة الدائمة', 'labor', 30, 'delete', 'حذف العمالة', 30, true),
('workers', 'العمالة الدائمة', 'labor', 30, 'sync', 'مزامنة العمالة', 40, true),
('temp_workers', 'العمالة المؤقتة', 'labor', 31, 'view', 'عرض العمالة المؤقتة', 0, true),
('temp_workers', 'العمالة المؤقتة', 'labor', 31, 'create', 'إضافة عامل مؤقت', 10, true),
('temp_workers', 'العمالة المؤقتة', 'labor', 31, 'edit', 'تعديل العمالة المؤقتة', 20, true),
('temp_workers', 'العمالة المؤقتة', 'labor', 31, 'delete', 'حذف العمالة المؤقتة', 30, true),
('work_visas', 'تأشيرات العمل', 'labor', 32, 'view', 'عرض تأشيرات العمل', 0, true),
('work_visas', 'تأشيرات العمل', 'labor', 32, 'edit', 'تعديل حالة الاستخدام', 10, true),
('invoices', 'الفواتير', 'invoice', 40, 'view', 'عرض الفواتير', 0, true),
('invoices', 'الفواتير', 'invoice', 40, 'create', 'إصدار فاتورة', 10, true),
('invoices', 'الفواتير', 'invoice', 40, 'edit', 'تعديل الفواتير', 20, true),
('invoices', 'الفواتير', 'invoice', 40, 'delete', 'حذف الفواتير', 30, true),
('invoices', 'الفواتير', 'invoice', 40, 'record_payment', 'تسجيل دفعة', 40, true),
('invoices', 'الفواتير', 'invoice', 40, 'cancel', 'إلغاء الفاتورة', 50, true),
('invoices', 'الفواتير', 'invoice', 40, 'refund', 'استرجاع الفاتورة', 60, true),
('invoices', 'الفواتير', 'invoice', 40, 'print', 'طباعة الفاتورة', 70, true),
('payments', 'سدادات الخدمات', 'receipt', 42, 'view', 'عرض المدفوعات', 0, true),
('payments', 'سدادات الخدمات', 'receipt', 42, 'pay', 'تسجيل سداد خدمة', 10, true),
('payments', 'سدادات الخدمات', 'receipt', 42, 'edit', 'تعديل السداد', 20, true),
('ext_payments', 'سدادات خارجية', 'receipt', 43, 'view', 'عرض السدادات الخارجية', 0, true),
('ext_payments', 'سدادات خارجية', 'receipt', 43, 'create', 'إضافة حوالة بنكية', 10, true),
('ext_payments', 'سدادات خارجية', 'receipt', 43, 'edit', 'تعديل السداد الخارجي', 20, true),
('deposits', 'الإيداعات', 'deposit', 41, 'view', 'عرض الإيداعات', 0, true),
('deposits', 'الإيداعات', 'deposit', 41, 'create', 'رفع طلب إيداع', 10, true),
('deposits', 'الإيداعات', 'deposit', 41, 'edit', 'تعديل الإيداعات', 20, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'view', 'عرض التسعيرات', 0, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'create', 'إنشاء تسعيرة', 10, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'price', 'تسعير', 20, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'approve', 'تصديق التسعيرة', 30, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'invoice', 'إصدار فاتورة من التسعيرة', 40, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'edit', 'تعديل التسعيرة', 50, true),
('quotations', 'تسعيرات التنازل', 'calc', 50, 'delete', 'حذف تسعيرة', 60, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'view', 'عرض تسعيرات التجديد', 0, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'create', 'إنشاء تسعيرة تجديد', 10, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'price', 'تسعير', 20, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'approve', 'تصديق التسعيرة', 30, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'invoice', 'إصدار فاتورة من التسعيرة', 40, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'edit', 'تعديل التسعيرة', 50, true),
('renewal_calc', 'تسعيرات التجديد', 'refresh', 51, 'delete', 'حذف التسعيرة', 60, true),
('sync_hub', 'مركز المزامنة', 'facility', 110, 'access', 'الوصول لمركز المزامنة', 0, true),
('sync_hub', 'مركز المزامنة', 'facility', 110, 'sync', 'تنفيذ المزامنة', 10, true),
('sync_hub', 'مركز المزامنة', 'facility', 110, 'manage_operator', 'إدارة المشغّل', 20, true),
('saudization', 'السعودة', 'tasks', 80, 'view', 'عرض السعودة', 0, true),
('saudization', 'السعودة', 'tasks', 80, 'create', 'إضافة معاملة سعودة', 10, true),
('saudization', 'السعودة', 'tasks', 80, 'edit', 'تعديل', 20, true),
('saudization', 'السعودة', 'tasks', 80, 'complete', 'تأكيد الإنجاز', 30, true),
('admin_clients', 'العملاء', 'clients', 90, 'view', 'عرض العملاء', 0, true),
('admin_clients', 'العملاء', 'clients', 90, 'create', 'إضافة عميل', 10, true),
('admin_clients', 'العملاء', 'clients', 90, 'edit', 'تعديل العملاء', 20, true),
('admin_clients', 'العملاء', 'clients', 90, 'delete', 'حذف العملاء', 30, true),
('admin_agents', 'الوسطاء', 'broker', 91, 'view', 'عرض الوسطاء', 0, true),
('admin_agents', 'الوسطاء', 'broker', 91, 'create', 'إضافة وسيط', 10, true),
('admin_agents', 'الوسطاء', 'broker', 91, 'edit', 'تعديل الوسطاء', 20, true),
('admin_agents', 'الوسطاء', 'broker', 91, 'delete', 'حذف الوسطاء', 30, true),
('admin_offices', 'المكاتب', 'branch', 100, 'view', 'عرض المكاتب', 0, true),
('admin_offices', 'المكاتب', 'branch', 100, 'create', 'إضافة مكتب', 10, true),
('admin_offices', 'المكاتب', 'branch', 100, 'edit', 'تعديل المكاتب', 20, true),
('admin_offices', 'المكاتب', 'branch', 100, 'delete', 'حذف المكاتب', 30, true),
('admin_bank_accounts', 'الحسابات البنكية', 'bank', 101, 'view', 'عرض الحسابات البنكية', 0, true),
('admin_bank_accounts', 'الحسابات البنكية', 'bank', 101, 'create', 'إضافة حساب بنكي', 10, true),
('admin_bank_accounts', 'الحسابات البنكية', 'bank', 101, 'edit', 'تعديل الحسابات البنكية', 20, true),
('admin_bank_accounts', 'الحسابات البنكية', 'bank', 101, 'delete', 'حذف الحسابات البنكية', 30, true),
('admin_permissions', 'المستخدمون والصلاحيات', 'userPerm', 102, 'view', 'عرض المستخدمين', 0, true),
('admin_permissions', 'المستخدمون والصلاحيات', 'userPerm', 102, 'create', 'إضافة مستخدم', 10, true),
('admin_permissions', 'المستخدمون والصلاحيات', 'userPerm', 102, 'edit', 'تعديل المستخدمين', 20, true),
('admin_permissions', 'المستخدمون والصلاحيات', 'userPerm', 102, 'manage_permissions', 'إدارة الصلاحيات', 30, true),
('admin_services', 'إدارة الخدمات', 'notes', 103, 'view', 'عرض إدارة الخدمات', 0, true),
('admin_services', 'إدارة الخدمات', 'notes', 103, 'edit', 'تعديل الخدمات', 10, true),
('admin_fees', 'الرسوم', 'payment', 104, 'view', 'عرض الرسوم', 0, true),
('admin_fees', 'الرسوم', 'payment', 104, 'create', 'إضافة رسم', 10, true),
('admin_fees', 'الرسوم', 'payment', 104, 'edit', 'تعديل الرسوم', 20, true),
('admin_fees', 'الرسوم', 'payment', 104, 'delete', 'حذف الرسوم', 30, true),
('settings_fields', 'الحقول', 'settings', 105, 'view', 'عرض الحقول', 0, true),
('settings_fields', 'الحقول', 'settings', 105, 'create', 'إضافة خانة/عنصر', 10, true),
('settings_fields', 'الحقول', 'settings', 105, 'edit', 'تعديل الحقول', 20, true),
('settings_fields', 'الحقول', 'settings', 105, 'delete', 'حذف الحقول', 30, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'view', 'عرض المعاملات', 0, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'create', 'طلب خدمة جديد', 10, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'edit', 'تعديل المعاملة', 20, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'delete', 'حذف المعاملة', 30, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'attach', 'إدارة المرفقات', 60, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'issue_visa', 'إصدار التأشيرة', 70, true),
('svc_work_visa_permanent', 'تأشيرة وإقامة دائمة', 'transaction', 60, 'register_iqama', 'تسجيل الإقامة', 80, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'view', 'عرض المعاملات', 0, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'create', 'طلب خدمة جديد', 10, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'edit', 'تعديل المعاملة', 20, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'delete', 'حذف المعاملة', 30, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'attach', 'إدارة المرفقات', 60, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'issue_visa', 'إصدار التأشيرة', 70, true),
('svc_work_visa_temporary', 'تأشيرة وإقامة مؤقتة', 'transaction', 61, 'register_iqama', 'تسجيل الإقامة', 80, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'view', 'عرض المعاملات', 0, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'create', 'طلب خدمة جديد', 10, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'edit', 'تعديل المعاملة', 20, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'delete', 'حذف المعاملة', 30, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_transfer', 'نقل كفالة', 'transaction', 62, 'attach', 'إدارة المرفقات', 60, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'view', 'عرض المعاملات', 0, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'create', 'طلب خدمة جديد', 10, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'edit', 'تعديل المعاملة', 20, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'delete', 'حذف المعاملة', 30, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_iqama_renewal', 'تجديد الإقامة', 'transaction', 63, 'attach', 'إدارة المرفقات', 60, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'view', 'عرض المعاملات', 0, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'create', 'طلب خدمة جديد', 10, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'edit', 'تعديل المعاملة', 20, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'delete', 'حذف المعاملة', 30, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_ajeer', 'عقد أجير', 'transaction', 64, 'attach', 'إدارة المرفقات', 60, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'view', 'عرض المعاملات', 0, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'create', 'طلب خدمة جديد', 10, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'edit', 'تعديل المعاملة', 20, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'delete', 'حذف المعاملة', 30, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_chamber', 'الغرفة التجارية', 'transaction', 65, 'attach', 'إدارة المرفقات', 60, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'view', 'عرض المعاملات', 0, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'create', 'طلب خدمة جديد', 10, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'edit', 'تعديل المعاملة', 20, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'delete', 'حذف المعاملة', 30, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_medical_insurance', 'تأمين طبي', 'transaction', 66, 'attach', 'إدارة المرفقات', 60, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'view', 'عرض المعاملات', 0, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'create', 'طلب خدمة جديد', 10, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'edit', 'تعديل المعاملة', 20, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'delete', 'حذف المعاملة', 30, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_profession_change', 'تغيير المهنة', 'transaction', 67, 'attach', 'إدارة المرفقات', 60, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'view', 'عرض المعاملات', 0, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'create', 'طلب خدمة جديد', 10, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'edit', 'تعديل المعاملة', 20, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'delete', 'حذف المعاملة', 30, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_external_transfer', 'الموافقة للنقل الخارجي', 'transaction', 68, 'attach', 'إدارة المرفقات', 60, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'view', 'عرض المعاملات', 0, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'create', 'طلب خدمة جديد', 10, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'edit', 'تعديل المعاملة', 20, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'delete', 'حذف المعاملة', 30, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_salary', 'تعديل الراتب', 'transaction', 69, 'attach', 'إدارة المرفقات', 60, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'view', 'عرض المعاملات', 0, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'create', 'طلب خدمة جديد', 10, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'edit', 'تعديل المعاملة', 20, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'delete', 'حذف المعاملة', 30, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_exit_reentry', 'خروج وعودة', 'transaction', 70, 'attach', 'إدارة المرفقات', 60, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'view', 'عرض المعاملات', 0, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'create', 'طلب خدمة جديد', 10, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'edit', 'تعديل المعاملة', 20, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'delete', 'حذف المعاملة', 30, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_final_exit', 'خروج نهائي', 'transaction', 71, 'attach', 'إدارة المرفقات', 60, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'view', 'عرض المعاملات', 0, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'create', 'طلب خدمة جديد', 10, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'edit', 'تعديل المعاملة', 20, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'delete', 'حذف المعاملة', 30, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_passport_update', 'تحديث بيانات الجواز', 'transaction', 72, 'attach', 'إدارة المرفقات', 60, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'view', 'عرض المعاملات', 0, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'create', 'طلب خدمة جديد', 10, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'edit', 'تعديل المعاملة', 20, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'delete', 'حذف المعاملة', 30, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_iqama_print', 'طباعة الإقامة', 'transaction', 73, 'attach', 'إدارة المرفقات', 60, true),
('svc_documents', 'مستندات', 'transaction', 74, 'view', 'عرض المعاملات', 0, true),
('svc_documents', 'مستندات', 'transaction', 74, 'create', 'طلب خدمة جديد', 10, true),
('svc_documents', 'مستندات', 'transaction', 74, 'edit', 'تعديل المعاملة', 20, true),
('svc_documents', 'مستندات', 'transaction', 74, 'delete', 'حذف المعاملة', 30, true),
('svc_documents', 'مستندات', 'transaction', 74, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_documents', 'مستندات', 'transaction', 74, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_documents', 'مستندات', 'transaction', 74, 'attach', 'إدارة المرفقات', 60, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'view', 'عرض المعاملات', 0, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'create', 'طلب خدمة جديد', 10, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'edit', 'تعديل المعاملة', 20, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'delete', 'حذف المعاملة', 30, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_supplier_payroll', 'طلب رواتب سبلاير', 'transaction', 75, 'attach', 'إدارة المرفقات', 60, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'view', 'عرض المعاملات', 0, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'create', 'طلب خدمة جديد', 10, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'edit', 'تعديل المعاملة', 20, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'delete', 'حذف المعاملة', 30, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'complete', 'تأكيد الإنجاز', 40, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'cancel', 'إلغاء المعاملة', 50, true),
('svc_general', 'خدمة عامة', 'transaction', 76, 'attach', 'إدارة المرفقات', 60, true),
('svc_accountant_approvals', 'موافقات المحاسب', 'transaction', 77, 'view', 'عرض الموافقات', 0, true),
('svc_accountant_approvals', 'موافقات المحاسب', 'transaction', 77, 'approve', 'موافقة المحاسب', 10, true),
('svc_accountant_approvals', 'موافقات المحاسب', 'transaction', 77, 'reject', 'رفض الطلب', 20, true)
ON CONFLICT (module, action) DO UPDATE SET
  module_label_ar = EXCLUDED.module_label_ar,
  module_icon     = EXCLUDED.module_icon,
  module_sort     = EXCLUDED.module_sort,
  label_ar        = EXCLUDED.label_ar,
  sort_order      = EXCLUDED.sort_order,
  is_active       = true;

