// ═══ Service Detection & SVG Logos ═══
// Maps sender domains/keywords to service info with inline SVG logos

const SERVICES = {
  // Government — official brand colors
  qiwa: { name: 'منصة قوى', domain: 'QIWA.SA', cat: 'gov', color: '#00a651', abbr: 'قوى',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00a65120"/><text x="20" y="17" text-anchor="middle" font-size="11" font-weight="900" fill="#00a651" font-family="Arial">QIWA</text><text x="20" y="30" text-anchor="middle" font-size="10" font-weight="800" fill="#00a651" font-family="Cairo">قوى</text></svg>` },
  absher: { name: 'أبشر', domain: 'ABSHER.SA', cat: 'gov', color: '#006838', abbr: 'أبشر',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00683820"/><text x="20" y="25" text-anchor="middle" font-size="12" font-weight="900" fill="#006838" font-family="Cairo">أبشر</text></svg>` },
  nafath: { name: 'نفاذ', domain: 'NAFATH.SA', cat: 'gov', color: '#1B998B', abbr: 'نفاذ',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1B998B20"/><circle cx="20" cy="16" r="6" fill="none" stroke="#1B998B" stroke-width="2"/><path d="M20 10 A6 6 0 0 1 26 16" fill="none" stroke="#1B998B" stroke-width="3" stroke-linecap="round"/><text x="20" y="34" text-anchor="middle" font-size="8" font-weight="800" fill="#1B998B" font-family="Cairo">نفاذ</text></svg>` },
  moi: { name: 'وزارة الداخلية', domain: 'MOI.GOV.SA', cat: 'gov', color: '#1a5c3a', abbr: 'داخلية',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1a5c3a18"/><path d="M20 6 L30 13 V22 C30 28 20 34 20 34 C20 34 10 28 10 22 V13 Z" fill="#1a5c3a15" stroke="#1a5c3a" stroke-width="1.5"/><text x="20" y="23" text-anchor="middle" font-size="8" font-weight="900" fill="#1a5c3a" font-family="Cairo">داخلية</text></svg>` },
  muqeem: { name: 'مقيم', domain: 'MUQEEM.SA', cat: 'gov', color: '#0d7c4a', abbr: 'مقيم',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#0d7c4a20"/><text x="20" y="25" text-anchor="middle" font-size="12" font-weight="900" fill="#0d7c4a" font-family="Cairo">مقيم</text></svg>` },
  gosi: { name: 'التأمينات', domain: 'GOSI.GOV.SA', cat: 'gov', color: '#00796B', abbr: 'GOSI',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00796B20"/><text x="20" y="18" text-anchor="middle" font-size="10" font-weight="900" fill="#00796B" font-family="Arial">GOSI</text><text x="20" y="30" text-anchor="middle" font-size="8" font-weight="700" fill="#00796B" font-family="Cairo">التأمينات</text></svg>` },
  tawakkalna: { name: 'توكلنا', domain: 'TAWAKKALNA.SA', cat: 'gov', color: '#00897B', abbr: 'توكلنا',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00897B20"/><text x="20" y="25" text-anchor="middle" font-size="11" font-weight="900" fill="#00897B" font-family="Cairo">توكلنا</text></svg>` },
  mol: { name: 'وزارة العمل', domain: 'MOL.GOV.SA', cat: 'gov', color: '#2e7d32', abbr: 'العمل',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#2e7d3220"/><text x="20" y="25" text-anchor="middle" font-size="11" font-weight="900" fill="#2e7d32" font-family="Cairo">العمل</text></svg>` },

  // Banks — official brand colors
  rajhi: { name: 'الراجحي', domain: 'ALRAJHIBANK.COM', cat: 'bank', color: '#004D40', abbr: 'الراجحي',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#004D4020"/><text x="20" y="18" text-anchor="middle" font-size="8" font-weight="900" fill="#004D40" font-family="Cairo">الراجحي</text><rect x="8" y="22" width="24" height="2" rx="1" fill="#004D40"/><rect x="12" y="26" width="16" height="6" rx="1" fill="#004D40" opacity=".3"/></svg>` },
  ahli: { name: 'الأهلي', domain: 'SNB.COM', cat: 'bank', color: '#006A4E', abbr: 'SNB',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#006A4E20"/><text x="20" y="18" text-anchor="middle" font-size="12" font-weight="900" fill="#006A4E" font-family="Arial">SNB</text><text x="20" y="30" text-anchor="middle" font-size="8" font-weight="700" fill="#006A4E" font-family="Cairo">الأهلي</text></svg>` },
  riyad: { name: 'بنك الرياض', domain: 'RIYADBANK.COM', cat: 'bank', color: '#7B2D8E', abbr: 'الرياض',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#7B2D8E20"/><text x="20" y="18" text-anchor="middle" font-size="7" font-weight="800" fill="#7B2D8E" font-family="Cairo">بنك الرياض</text><rect x="10" y="22" width="20" height="2" rx="1" fill="#7B2D8E"/><text x="20" y="34" text-anchor="middle" font-size="8" font-weight="700" fill="#7B2D8E" font-family="Arial">RIYAD</text></svg>` },
  bilad: { name: 'بنك البلاد', domain: 'BANKALBILAD.COM', cat: 'bank', color: '#B71C1C', abbr: 'البلاد',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#B71C1C20"/><text x="20" y="18" text-anchor="middle" font-size="7" font-weight="800" fill="#B71C1C" font-family="Cairo">بنك البلاد</text><rect x="10" y="22" width="20" height="2" rx="1" fill="#B71C1C"/><text x="20" y="34" text-anchor="middle" font-size="8" font-weight="700" fill="#B71C1C" font-family="Arial">BILAD</text></svg>` },
  stcpay: { name: 'STC Pay', domain: 'STCPAY.COM', cat: 'bank', color: '#4A148C', abbr: 'STC',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#4A148C20"/><text x="20" y="18" text-anchor="middle" font-size="12" font-weight="900" fill="#4A148C" font-family="Arial">stc</text><text x="20" y="30" text-anchor="middle" font-size="9" font-weight="800" fill="#4A148C" font-family="Arial">pay</text></svg>` },

  // Default
  _default: { name: 'غير معروف', domain: '', cat: 'other', color: '#9b59b6',
    logo: (s=40)=>`<svg width="${s}" height="${s}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#9b59b618"/><circle cx="20" cy="16" r="5" fill="none" stroke="#9b59b6" stroke-width="1.5"/><path d="M12 30 C12 24 15 22 20 22 C25 22 28 24 28 30" fill="none" stroke="#9b59b6" stroke-width="1.5"/></svg>` }
}

export function detectService(sender) {
  const s = (sender || '').toLowerCase()
  if (s.includes('qiwa') || s.includes('mol.gov')) return SERVICES.qiwa
  if (s.includes('absher')) return SERVICES.absher
  if (s.includes('nafath') || s.includes('nfath')) return SERVICES.nafath
  if (s.includes('muqeem') || s.includes('mqeem')) return SERVICES.muqeem
  if (s.includes('gosi') || s.includes('taminat')) return SERVICES.gosi
  if (s.includes('tawakkalna') || s.includes('twklna')) return SERVICES.tawakkalna
  if (s.includes('moi') || s.includes('dakhili')) return SERVICES.moi
  if (s.includes('mol') && !s.includes('qiwa')) return SERVICES.mol
  if (s.includes('rajhi')) return SERVICES.rajhi
  if (s.includes('ahli') || s.includes('snb')) return SERVICES.ahli
  if (s.includes('riyad')) return SERVICES.riyad
  if (s.includes('bilad')) return SERVICES.bilad
  if (s.includes('stc') && s.includes('pay')) return SERVICES.stcpay
  if (s.includes('iam') || s.includes('nafath') || s.includes('nfath') || s.includes('نفاذ')) return SERVICES.nafath
  if (s.includes('jawazat') || s.includes('جوازات')) return { ...SERVICES._default, name: 'الجوازات', domain: 'MOI-JAWAZAT', cat: 'gov', color: '#1a5c3a', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1a5c3a20"/><text x="20" y="25" text-anchor="middle" font-size="10" font-weight="900" fill="#1a5c3a" font-family="Cairo">الجوازات</text></svg>` }
  if (s.includes('moroor') || s.includes('مرور')) return { ...SERVICES._default, name: 'المرور', domain: 'MOI-MOROOR', cat: 'gov', color: '#2E7D32', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#2E7D3220"/><text x="20" y="25" text-anchor="middle" font-size="11" font-weight="900" fill="#2E7D32" font-family="Cairo">المرور</text></svg>` }
  if (s.includes('moj') || s.includes('العدل')) return { ...SERVICES._default, name: 'وزارة العدل', domain: 'MOJ.GOV.SA', cat: 'gov', color: '#00695C', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00695C20"/><text x="20" y="25" text-anchor="middle" font-size="9" font-weight="900" fill="#00695C" font-family="Cairo">العدل</text></svg>` }
  if (s.includes('mc.gov') || s.includes('التجارة')) return { ...SERVICES._default, name: 'وزارة التجارة', domain: 'MC.GOV.SA', cat: 'gov', color: '#1B5E20', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1B5E2020"/><text x="20" y="25" text-anchor="middle" font-size="9" font-weight="900" fill="#1B5E20" font-family="Cairo">التجارة</text></svg>` }
  if (s.includes('sbc')) return { ...SERVICES._default, name: 'المركز السعودي للأعمال', domain: 'SBC.SA', cat: 'gov', color: '#1565C0', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1565C020"/><text x="20" y="18" text-anchor="middle" font-size="10" font-weight="900" fill="#1565C0" font-family="Arial">SBC</text><text x="20" y="30" text-anchor="middle" font-size="6" font-weight="700" fill="#1565C0" font-family="Cairo">المركز السعودي</text></svg>` }
  if (s.includes('eastchamber') || s.includes('abhacci') || s.includes('الغرفة') || s.includes('chamber')) return { ...SERVICES._default, name: 'الغرفة التجارية', domain: 'CHAMBER', cat: 'gov', color: '#0D47A1', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#0D47A120"/><text x="20" y="24" text-anchor="middle" font-size="7" font-weight="900" fill="#0D47A1" font-family="Cairo">الغرفة التجارية</text></svg>` }
  if (s.includes('efaa') || s.includes('إيفاء')) return { ...SERVICES._default, name: 'إيفاء', domain: 'EFAA.SA', cat: 'gov', color: '#AD1457', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#AD145720"/><text x="20" y="25" text-anchor="middle" font-size="12" font-weight="900" fill="#AD1457" font-family="Cairo">إيفاء</text></svg>` }
  if (s.includes('hrsd') || s.includes('ajeer') || s.includes('أجير')) return { ...SERVICES._default, name: 'أجير', domain: 'HRSD.GOV.SA', cat: 'gov', color: '#00838F', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00838F20"/><text x="20" y="25" text-anchor="middle" font-size="12" font-weight="900" fill="#00838F" font-family="Cairo">أجير</text></svg>` }
  if (s.includes('zatca') || s.includes('الزكاة')) return { ...SERVICES._default, name: 'هيئة الزكاة', domain: 'ZATCA.GOV.SA', cat: 'gov', color: '#4E342E', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#4E342E20"/><text x="20" y="25" text-anchor="middle" font-size="9" font-weight="900" fill="#4E342E" font-family="Cairo">الزكاة</text></svg>` }
  if (s.includes('mudad') || s.includes('مدد')) return { ...SERVICES._default, name: 'مدد', domain: 'MUDAD.SA', cat: 'gov', color: '#0D47A1', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#0D47A120"/><text x="20" y="25" text-anchor="middle" font-size="13" font-weight="900" fill="#0D47A1" font-family="Cairo">مدد</text></svg>` }
  if (s.includes('monshaat') || s.includes('منشآت')) return { ...SERVICES._default, name: 'منشآت', domain: 'MONSHAAT.GOV.SA', cat: 'gov', color: '#00796B', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00796B20"/><text x="20" y="25" text-anchor="middle" font-size="11" font-weight="900" fill="#00796B" font-family="Cairo">منشآت</text></svg>` }
  if (s.includes('spl') || s.includes('البريد')) return { ...SERVICES._default, name: 'البريد السعودي', domain: 'SPL.SA', cat: 'other', color: '#1B5E20', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1B5E2020"/><text x="20" y="18" text-anchor="middle" font-size="10" font-weight="900" fill="#1B5E20" font-family="Arial">SPL</text><text x="20" y="30" text-anchor="middle" font-size="7" font-weight="700" fill="#1B5E20" font-family="Cairo">البريد</text></svg>` }
  if (s.includes('tameeni') || s.includes('تأميني')) return { ...SERVICES._default, name: 'تأميني', domain: 'TAMEENI.COM', cat: 'other', color: '#E65100', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#E6510020"/><text x="20" y="25" text-anchor="middle" font-size="11" font-weight="900" fill="#E65100" font-family="Cairo">تأميني</text></svg>` }
  if (s.includes('tamm') || s.includes('تم')) return { ...SERVICES._default, name: 'تمّ', domain: 'TAMM.SA', cat: 'gov', color: '#00897B', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00897B20"/><text x="20" y="25" text-anchor="middle" font-size="14" font-weight="900" fill="#00897B" font-family="Cairo">تمّ</text></svg>` }
  if (s.includes('kahraba') || s.includes('كهرباء')) return { ...SERVICES._default, name: 'الكهرباء', domain: 'SE.COM.SA', cat: 'other', color: '#F57F17', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#F57F1720"/><text x="20" y="25" text-anchor="middle" font-size="10" font-weight="900" fill="#F57F17" font-family="Cairo">الكهرباء</text></svg>` }
  if (s.includes('civildef') || s.includes('الدفاع المدني')) return { ...SERVICES._default, name: 'الدفاع المدني', domain: 'CIVILDEF', cat: 'gov', color: '#BF360C', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#BF360C20"/><text x="20" y="24" text-anchor="middle" font-size="7" font-weight="900" fill="#BF360C" font-family="Cairo">الدفاع المدني</text></svg>` }
  if (s.includes('aramex') || s.includes('أرامكس')) return { ...SERVICES._default, name: 'أرامكس', domain: 'ARAMEX.COM', cat: 'other', color: '#E53935', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#E5393520"/><text x="20" y="25" text-anchor="middle" font-size="10" font-weight="900" fill="#E53935" font-family="Cairo">أرامكس</text></svg>` }
  if (s.includes('google') || s.includes('جوجل')) return { ...SERVICES._default, name: 'جوجل', domain: 'GOOGLE.COM', cat: 'other', color: '#4285F4', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#4285F420"/><text x="20" y="26" text-anchor="middle" font-size="14" font-weight="900" fill="#4285F4" font-family="Arial">G</text></svg>` }
  if (s.includes('momah') || s.includes('الإسكان')) return { ...SERVICES._default, name: 'وزارة الإسكان', domain: 'MOMAH.GOV.SA', cat: 'gov', color: '#5D4037', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#5D403720"/><text x="20" y="25" text-anchor="middle" font-size="9" font-weight="900" fill="#5D4037" font-family="Cairo">الإسكان</text></svg>` }
  if (s.includes('freelance') || s.includes('العمل الحر')) return { ...SERVICES._default, name: 'العمل الحر', domain: 'FREELANCE.SA', cat: 'gov', color: '#00ACC1', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00ACC120"/><text x="20" y="24" text-anchor="middle" font-size="8" font-weight="900" fill="#00ACC1" font-family="Cairo">العمل الحر</text></svg>` }
  if (s.includes('worldofss')) return { ...SERVICES._default, name: 'خدمات حكومية', domain: 'WORLDOFSS', cat: 'gov', color: '#37474F', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#37474F20"/><text x="20" y="25" text-anchor="middle" font-size="8" font-weight="900" fill="#37474F" font-family="Cairo">خدمات حكومية</text></svg>` }
  if (s.includes('sdb')) return { ...SERVICES._default, name: 'بنك التنمية', domain: 'SDB.GOV.SA', cat: 'bank', color: '#1A237E', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#1A237E20"/><text x="20" y="18" text-anchor="middle" font-size="10" font-weight="900" fill="#1A237E" font-family="Arial">SDB</text><text x="20" y="30" text-anchor="middle" font-size="7" font-weight="700" fill="#1A237E" font-family="Cairo">بنك التنمية</text></svg>` }
  if (s.includes('mobily') || s.includes('موبايلي')) return { ...SERVICES._default, name: 'موبايلي', domain: 'MOBILY.COM', cat: 'other', color: '#6A1B9A', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#6A1B9A20"/><text x="20" y="18" text-anchor="middle" font-size="8" font-weight="900" fill="#6A1B9A" font-family="Arial">Mobily</text><text x="20" y="30" text-anchor="middle" font-size="9" font-weight="800" fill="#6A1B9A" font-family="Cairo">موبايلي</text></svg>` }
  if (s.includes('stc') && !s.includes('pay')) return { ...SERVICES._default, name: 'STC', domain: 'STC.COM', cat: 'other', color: '#4A148C', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#4A148C20"/><text x="20" y="26" text-anchor="middle" font-size="14" font-weight="900" fill="#4A148C" font-family="Arial">stc</text></svg>` }
  if (s.includes('zain') || s.includes('زين')) return { ...SERVICES._default, name: 'زين', domain: 'ZAIN.COM', cat: 'other', color: '#7B1FA2', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#7B1FA220"/><text x="20" y="25" text-anchor="middle" font-size="12" font-weight="900" fill="#7B1FA2" font-family="Cairo">زين</text></svg>` }
  if (s.includes('inma') || s.includes('انماء') || s.includes('الإنماء') || s.includes('alinma')) return { ...SERVICES._default, name: 'بنك الإنماء', domain: 'ALINMA.COM', cat: 'bank', color: '#00695c', logo: (sz=40)=>`<svg width="${sz}" height="${sz}" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#00695c20"/><text x="20" y="18" text-anchor="middle" font-size="7" font-weight="800" fill="#00695c" font-family="Cairo">بنك الإنماء</text><text x="20" y="30" text-anchor="middle" font-size="9" font-weight="900" fill="#00695c" font-family="Arial">INMA</text></svg>` }
  if (s.includes('bank') || s.includes('pay') || s.includes('mada')) return { ...SERVICES._default, name: sender || 'بنك', domain: sender || '', cat: 'bank', color: '#e67e22' }
  if (s.includes('gov')) return { ...SERVICES._default, name: sender || 'حكومي', domain: sender || '', cat: 'gov', color: '#1abc9c' }
  return { ...SERVICES._default, name: sender || 'غير معروف', domain: sender || '' }
}

export default SERVICES
