// Generates sweep.generated.js for the Qiwa sync Chrome extension.
// ────────────────────────────────────────────────────────────────
// Single source of truth: src/pages/qiwaSyncBookmarklet.js → qiwaSweepBody().
// The bookmarklet body is written for a page context (DOM + one origin). Here we
// transform it for an MV3 background service worker:
//   1. Turn the immediately-invoked `(async () => { … })()` into a callable
//      `self.__runQiwaSweep = async () => { … }` (runs on demand, not on load).
//   2. Replace the DOM-based `msg()` progress UI with chrome.runtime messaging.
//   3. Drop the `location.hostname` guard (a SW has no qiwa.sa location).
//   4. Drop the DOM cleanup timer.
// Everything else — every endpoint, the per-company context-switch sweep, the
// Supabase writes — is reused verbatim, so the extension never drifts from the
// bookmarklet.
//
// Run:  node qiwa-sync-extension/build.mjs
import { qiwaSweepBody } from '../src/pages/qiwaSyncBookmarklet.js'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))

let src = qiwaSweepBody({ sourceId: 'qiwa', personId: '' })

// (1) IIFE → named, on-demand function on the SW global.
const iifeOpen = '(async () => {'
if (!src.includes(iifeOpen)) throw new Error('build: could not find outer IIFE opener')
src = src.replace(iifeOpen, 'self.__runQiwaSweep = async () => {')
// The matching close is the final `})();` in the file.
if (!/\}\)\(\);\s*$/.test(src.trimEnd() + '\n')) {
  // fall through — replace the last occurrence explicitly below
}
{
  const idx = src.lastIndexOf('})();')
  if (idx === -1) throw new Error('build: could not find outer IIFE closer')
  src = src.slice(0, idx) + '};' + src.slice(idx + '})();'.length)
}

// (2) DOM msg() → chrome.runtime progress messages (best-effort; popup may be closed).
const msgRe = /const msg = \(m\) => \{[\s\S]*?\n  \};/
if (!msgRe.test(src)) throw new Error('build: could not find msg() definition')
src = src.replace(
  msgRe,
  "const msg = (m) => { const t = 'جسر قوى: ' + m; try { chrome.runtime.sendMessage({ type: 'qiwa-progress', text: t }); } catch (e) {} console.log('[qiwa-ext]', t); return null; };"
)

// (2b) sync_runs has RLS `sync_runs_anon_write` = is_active_sync_person(person_id),
// so the insert needs a valid sync_persons.id — an empty string / null is rejected
// and aborts the whole sweep. The extension supplies the id via a global that
// background.js sets from config (self.__QIWA_PERSON_ID).
if (!src.includes("PERSON = ''")) throw new Error("build: expected PERSON = '' literal")
src = src.replace("PERSON = ''", 'PERSON = (self.__QIWA_PERSON_ID || null)')

// (3) Drop the hostname guard.
src = src.replace(/\n\s*if \(!location\.hostname\.endsWith\('qiwa\.sa'\)\)[^\n]*\n/, '\n')

// (4) Drop the DOM cleanup timer.
src = src.replace(/\n\s*setTimeout\(\(\) => \{ document\.getElementById[^\n]*\n/, '\n')

if (/document\.|location\.hostname/.test(src)) {
  throw new Error('build: DOM/location references still present after transform — aborting')
}

const header = `// AUTO-GENERATED by qiwa-sync-extension/build.mjs — DO NOT EDIT.
// Source of truth: src/pages/qiwaSyncBookmarklet.js (qiwaSweepBody).
// Defines self.__runQiwaSweep(): the full Qiwa sweep, adapted for an MV3 SW.
/* eslint-disable */
`

const outPath = join(__dirname, 'sweep.generated.js')
writeFileSync(outPath, header + src + '\n', 'utf8')
console.log('✓ wrote', outPath, `(${(header + src).length} bytes)`)
